/* ============================================================================
   Global IPO Tracker: dataset
   ----------------------------------------------------------------------------
   Every row is compiled from public sources: exchange filings and calendars,
   regulator approvals (Saudi CMA), company press releases, and financial press
   reporting. Each record carries its own `sources` array and `verified` date so
   any figure on the dashboard can be traced back to where it came from.

   CONTACT DATA METHODOLOGY
   ------------------------
   Executive email addresses are almost never published. Rather than invent
   them, every address on this dashboard carries an explicit confidence tier:

     "verified": the address is published by the company itself (an investor
                  relations or corporate mailbox). Traceable via `sources`.
     "inferred": the company's email pattern is known (confirmed from a
                  published address at the same domain, or from the domain's
                  documented convention) and the executive's address is
                  constructed from it. Shown with the pattern that produced it.
                  NOT a confirmed working address.
     "none":     no public basis for an address. Displayed as N/A.

   An analyst using this list should treat "inferred" as a starting hypothesis
   for outreach, not as a verified contact.

   `valuationUsdM` is an approximate USD normalisation used only to make the
   valuation column sortable across currencies. FX used (Sept 2026, indicative):
   EUR 1.16, GBP 1.34, SAR 0.267, BRL 0.185, MYR 0.237.
   ========================================================================== */

const IPO_DATA = [

  /* ===================== TADAWUL (Saudi Exchange) ======================== */
  {
    company: "Tabby",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "FinTech",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "Buy-now-pay-later platform operating across Saudi Arabia and the UAE with more than 15 million registered users. Redomiciled to Saudi Arabia ahead of a planned Tadawul listing; raised a $160m Series E at a $4.5bn valuation.",
    valuationDisplay: "$4.5bn",
    valuationUsdM: 4500,
    raiseDisplay: "N/A",
    ceo: "Hosam Arab",
    ceoEmail: "hosam.arab@tabby.ai",
    ceoEmailTier: "inferred",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: "first.last@tabby.ai",
    patternNote: "Domain confirmed (tabby.ai). Pattern assumed from regional fintech convention, treat as unverified.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" },
      { label: "Zawya, Tabby plans Tadawul listing", url: "https://www.zawya.com/en/markets/equities/bnpl-app-tabby-plans-ipo-saudi-tadawul-listing-mu2owg22" }
    ]
  },
  {
    company: "Tamara",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "FinTech",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Saudi Arabia's first BNPL unicorn, offering split-payment and consumer credit products across the GCC. Secured a $2.4bn debt facility backed by Goldman Sachs to fund receivables growth ahead of listing.",
    valuationDisplay: "$1.5–2.0bn",
    valuationUsdM: 1750,
    raiseDisplay: "$400–600m",
    ceo: "Abdulmajeed Alsukhan",
    ceoEmail: "abdulmajeed.alsukhan@tamara.co",
    ceoEmailTier: "inferred",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: "first.last@tamara.co",
    patternNote: "Domain confirmed (tamara.co). Pattern unverified.",
    verified: "2026-09-02",
    sources: [
      { label: "Invest Riyadh, Tadawul IPO pipeline", url: "https://investriyadh.ai/intelligence/tadawul-ipo-boom/" },
      { label: "FinTech Futures, Tamara $2.4bn facility", url: "https://www.fintechfutures.com/bnpl-payments/tamara-secures-2-4bn-facility" }
    ]
  },
  {
    company: "ROSHN Group",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Real Estate",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "PIF-owned multi-asset real estate developer building more than 400,000 homes across 10+ Saudi cities. One of the Vision 2030 giga-developers and a flagship candidate in the PIF privatisation programme.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Group CEO role in transition through 2026, no confirmed incumbent, so no name or address is asserted.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" },
      { label: "AGBI, PIF active in Saudi IPOs", url: "https://www.agbi.com/analysis/markets/2026/02/pif-to-be-active-in-saudi-ipos-this-year-analysts-say/" }
    ]
  },
  {
    company: "Saudi Global Ports",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Transport & Logistics",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "Container terminal operator running the King Abdulaziz Port at Dammam. Joint venture between a PIF subsidiary and Singapore's PSA International; one of eight assets PIF has earmarked for IPO or secondary sale.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No public executive disclosure ahead of prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "AGBI, PIF active in Saudi IPOs", url: "https://www.agbi.com/analysis/markets/2026/02/pif-to-be-active-in-saudi-ipos-this-year-analysts-say/" }
    ]
  },
  {
    company: "National Water Company",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Utilities",
    status: "Announced",
    listingDate: "2026-Q4",
    datePrecision: "quarter",
    description: "State-owned water and wastewater utility serving the Kingdom's major urban clusters, being prepared for partial privatisation under the Vision 2030 asset programme.",
    valuationDisplay: "$4.0–5.0bn",
    valuationUsdM: 4500,
    raiseDisplay: "$1.0–1.5bn",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "State-owned issuer; executive contacts not published pre-prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "Invest Riyadh, Tadawul IPO pipeline", url: "https://investriyadh.ai/intelligence/tadawul-ipo-boom/" }
    ]
  },
  {
    company: "Saudi Entertainment Ventures (SEVEN)",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Consumer & Leisure",
    status: "Announced",
    listingDate: "2026-Q3",
    datePrecision: "quarter",
    description: "PIF-owned developer and operator of entertainment destinations across Saudi cities, building a national network of cinema, retail and leisure complexes.",
    valuationDisplay: "$2.0–3.0bn",
    valuationUsdM: 2500,
    raiseDisplay: "$500–800m",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No public executive disclosure ahead of prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "Invest Riyadh, Tadawul IPO pipeline", url: "https://investriyadh.ai/intelligence/tadawul-ipo-boom/" }
    ]
  },
  {
    company: "Alat (semiconductor JV)",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "AI & Semiconductors",
    status: "Rumoured",
    listingDate: "2026-Q3",
    datePrecision: "quarter",
    description: "PIF-backed industrial technology company building semiconductor, advanced electronics and smart-device manufacturing capacity in the Kingdom through international joint ventures.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Early-stage listing speculation; no filing.",
    verified: "2026-09-02",
    sources: [
      { label: "Invest Riyadh, Tadawul IPO pipeline", url: "https://investriyadh.ai/intelligence/tadawul-ipo-boom/" }
    ]
  },
  {
    company: "ArcelorMittal Jubail",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Metals & Mining",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Seamless steel tube manufacturer in Jubail with 600,000 tonnes of annual capacity, serving regional oil and gas customers. Joint venture with ArcelorMittal.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "JV entity; executive contacts not separately published.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Panda Retail Company",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Consumer Staples",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "Saudi Arabia's largest grocery chain with more than 200 hypermarkets and supermarkets. Carve-out from listed parent Savola Group.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Contact route runs through listed parent Savola Group's investor relations function.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "noon",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "E-Commerce",
    status: "Rumoured",
    listingDate: "2027",
    datePrecision: "year",
    description: "Regional e-commerce and quick-commerce platform backed by PIF and Mohamed Alabbar, operating across Saudi Arabia, the UAE and Egypt. A dual Tadawul / ADX listing has been discussed.",
    valuationDisplay: "~$10bn",
    valuationUsdM: 10000,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No confirmed executive disclosure for the listing entity.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Sela",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Consumer & Leisure",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "Events, ticketing and experience company founded in 1997 and acquired by PIF. Delivers major Saudi entertainment and sporting events; named by analysts as one of eight PIF assets earmarked for market.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No public executive disclosure ahead of prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "AGBI, PIF active in Saudi IPOs", url: "https://www.agbi.com/analysis/markets/2026/02/pif-to-be-active-in-saudi-ipos-this-year-analysts-say/" }
    ]
  },
  {
    company: "MGC Contracting",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Industrials",
    status: "Regulator-approved",
    listingDate: "2026",
    datePrecision: "year",
    description: "Contracting and capital-goods group founded in 1977, offering 30% of capital. CMA approval granted with a stated offering window.",
    valuationDisplay: "SAR 12–15bn",
    valuationUsdM: 3600,
    raiseDisplay: "30% of capital",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Executive detail sits in the Arabic-language prospectus, not in English disclosure.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Aldyar Alarabiya",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Real Estate",
    status: "Regulator-approved",
    listingDate: "2026",
    datePrecision: "year",
    description: "Jeddah-based property developer with a SAR 15bn portfolio. CMA-approved offering of 97.5m shares, representing 30% of capital.",
    valuationDisplay: "SAR 15bn portfolio",
    valuationUsdM: 4000,
    raiseDisplay: "97.5m shares (30%)",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Executive detail sits in the Arabic-language prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Alandalus Education",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Education",
    status: "Regulator-approved",
    listingDate: "2026",
    datePrecision: "year",
    description: "Private K-12 education operator running 10 campuses with more than 18,000 students. CMA-approved offering of 30% of capital.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "30% of capital",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Executive detail sits in the Arabic-language prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Alkhorayef Petroleum",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Energy",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "Oilfield services business manufacturing and servicing electric submersible pumps for regional upstream operators. PIF holds a 25% stake.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No public executive disclosure ahead of prospectus.",
    verified: "2026-09-02",
    sources: [
      { label: "decoded.finance Saudi IPO calendar", url: "https://decoded.finance/ipo-calendar/" }
    ]
  },
  {
    company: "Saudia Airlines",
    exchange: "TADAWUL",
    country: "Saudi Arabia",
    sector: "Aviation",
    status: "Rumoured",
    listingDate: "2027",
    datePrecision: "year",
    description: "National flag carrier undergoing comprehensive restructuring and fleet modernisation ahead of a possible partial privatisation.",
    valuationDisplay: "$10–15bn",
    valuationUsdM: 12500,
    raiseDisplay: "$2–3bn",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "State-owned issuer; no listing-entity disclosure yet.",
    verified: "2026-09-02",
    sources: [
      { label: "Invest Riyadh, Tadawul IPO pipeline", url: "https://investriyadh.ai/intelligence/tadawul-ipo-boom/" }
    ]
  },

  /* ============================ LSE (London) ============================= */
  {
    company: "Monzo Bank",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "FinTech",
    status: "Announced",
    listingDate: "2027",
    datePrecision: "year",
    description: "UK digital challenger bank with over 12 million customers. Exited the US to concentrate on Europe ahead of listing; Morgan Stanley engaged to advise on a float. A board rift over IPO timing led to a CEO change in early 2026.",
    valuationDisplay: "~£6bn",
    valuationUsdM: 8040,
    raiseDisplay: "N/A",
    ceo: "Diana Layfield",
    ceoEmail: "diana.layfield@monzo.com",
    ceoEmailTier: "inferred",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: "first.last@monzo.com",
    patternNote: "Domain confirmed (monzo.com). Pattern assumed from UK corporate convention, unverified.",
    verified: "2026-09-02",
    sources: [
      { label: "City AM, Monzo names new chief", url: "https://www.cityam.com/monzo-names-new-chief-as-london-becomes-top-ipo-choice/" },
      { label: "TNW, Monzo quits US ahead of London IPO", url: "https://thenextweb.com/news/monzo-us-exit-europe-ipo" }
    ]
  },
  {
    company: "Visma",
    exchange: "LSE",
    country: "Norway / United Kingdom",
    sector: "Software",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Nordic business software and payroll group backed by Hg Capital, which selected London over Amsterdam for what would be one of the largest European technology listings in years.",
    valuationDisplay: "~£16.5bn",
    valuationUsdM: 22110,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Sponsor-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },
  {
    company: "RAC",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "Consumer Services",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "UK roadside assistance and motoring services group owned by a consortium including CVC and Silver Lake, long cited as a candidate to return to the public market.",
    valuationDisplay: "~£5bn",
    valuationUsdM: 6700,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Sponsor-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },
  {
    company: "Gymshark",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "Consumer Discretionary",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "Direct-to-consumer activewear brand founded in 2012, built on influencer-led marketing and online distribution. Founder-controlled, with General Atlantic holding a minority stake.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "Ben Francis",
    ceoEmail: "ben.francis@gymshark.com",
    ceoEmailTier: "inferred",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: "first.last@gymshark.com",
    patternNote: "Domain confirmed (gymshark.com). Pattern assumed from UK corporate convention, unverified.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" },
      { label: "Gymshark, Ben Francis returns as CEO", url: "https://fashionunited.uk/news/business/gymshark-co-founder-ben-francis-returns-to-ceo-role/2021070256366" }
    ]
  },
  {
    company: "loveholidays",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "Travel & Leisure",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Online travel agency selling dynamically packaged flight-plus-hotel holidays, owned by Livingbridge. Listing was delayed from early 2026 amid market volatility.",
    valuationDisplay: "~£1bn",
    valuationUsdM: 1340,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Sponsor-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },
  {
    company: "Starling Bank",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "FinTech",
    status: "Rumoured",
    listingDate: "2027",
    datePrecision: "year",
    description: "UK digital bank with a profitable retail and SME franchise, plus the Engine banking-software business it licenses to other banks.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No confirmed listing process; contacts not asserted.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },
  {
    company: "SumUp",
    exchange: "LSE",
    country: "United Kingdom / Germany",
    sector: "FinTech",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "Merchant payments company providing card readers and business accounts to small merchants across Europe and Latin America. Cited alongside Monzo as a test of London's ability to retain fintech listings.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No confirmed listing process; contacts not asserted.",
    verified: "2026-09-02",
    sources: [
      { label: "City AM, London fintech IPO test", url: "https://www.cityam.com/monzo-names-new-chief-as-london-becomes-top-ipo-choice/" }
    ]
  },
  {
    company: "Waterstones",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "Consumer Discretionary",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "UK bookstore chain owned by Elliott Advisors, which also controls Barnes & Noble. A listing would test appetite for physical retail on the London market.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Sponsor-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },
  {
    company: "Boots",
    exchange: "LSE",
    country: "United Kingdom",
    sector: "Consumer Staples",
    status: "Rumoured",
    listingDate: "2027",
    datePrecision: "year",
    description: "UK pharmacy and health-and-beauty retailer owned by Walgreens Boots Alliance. A London listing has been revisited repeatedly since the abandoned 2024 sale process.",
    valuationDisplay: "~£7bn",
    valuationUsdM: 9380,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Parent-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Legal Cheek, UK IPOs in 2026", url: "https://www.legalcheek.com/lc-journal-posts/from-gymshark-to-monzo-uk-ipos-in-2026/" }
    ]
  },

  /* ====================== XETRA (Deutsche Börse) ========================= */
  {
    company: "TK Elevator",
    exchange: "XETRA",
    country: "Germany",
    sector: "Industrials",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "One of the world's four largest elevator and escalator manufacturers, spun out of Thyssenkrupp in 2020. Owned by Advent, Cinven and Thyssenkrupp; would be among the largest German listings in years.",
    valuationDisplay: "€23bn",
    valuationUsdM: 26680,
    raiseDisplay: "N/A",
    ceo: "Uday Yadav",
    ceoEmail: "uday.yadav@tkelevator.com",
    ceoEmailTier: "inferred",
    cfo: "Philipp Mueller",
    cfoEmail: "philipp.mueller@tkelevator.com",
    cfoEmailTier: "inferred",
    irEmail: "christian.h.schulte@tkelevator.com",
    irName: "Christian Schulte, Head of Investor Relations",
    irEmailTier: "verified",
    emailPattern: "first.last@tkelevator.com",
    patternNote: "Pattern CONFIRMED from the company's own published IR contacts (nicole.getta@tkelevator.com, christian.h.schulte@tkelevator.com). Executive addresses constructed from that confirmed pattern.",
    verified: "2026-09-02",
    sources: [
      { label: "TK Elevator Investor Relations (published contacts)", url: "https://investors.tkelevator.com" },
      { label: "Börsen-Zeitung, EY expects up to ten German IPOs in 2026", url: "https://www.boersen-zeitung.de/english/ey-expects-up-to-ten-german-ipos-in-2026" },
      { label: "TK Elevator, CFO Philipp Mueller", url: "https://www.tkelevator.com/global-en/about-us/leadership/philipp-mueller/" }
    ]
  },
  {
    company: "KNDS",
    exchange: "XETRA",
    country: "Germany / France",
    sector: "Defence",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Franco-German land-defence group formed from Krauss-Maffei Wegmann and Nexter, producing the Leopard 2 tank and artillery systems. A listing would ride the European rearmament cycle.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "State-shareholder structure; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Börsen-Zeitung, EY expects up to ten German IPOs in 2026", url: "https://www.boersen-zeitung.de/english/ey-expects-up-to-ten-german-ipos-in-2026" }
    ]
  },
  {
    company: "mobile.de",
    exchange: "XETRA",
    country: "Germany",
    sector: "Internet & Classifieds",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "Germany's largest online vehicle marketplace, acquired from Adevinta by Blackstone and Permira. A classic sponsor-exit candidate for the Frankfurt market.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Sponsor-controlled process; no listing-entity contacts published.",
    verified: "2026-09-02",
    sources: [
      { label: "Börsen-Zeitung, EY expects up to ten German IPOs in 2026", url: "https://www.boersen-zeitung.de/english/ey-expects-up-to-ten-german-ipos-in-2026" }
    ]
  },
  {
    company: "Brainlab",
    exchange: "XETRA",
    country: "Germany",
    sector: "Biotech & MedTech",
    status: "Postponed",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "Medical technology company making software-guided surgical navigation systems for brain, tumour and spinal procedures, and radiotherapy guidance. Describes itself as 'the Google Maps for surgery'. Generated €470m revenue at a 16.5% EBITDA margin; the 2025 Prime Standard listing was pulled and has not been relaunched.",
    valuationDisplay: "~€3bn (2025 attempt)",
    valuationUsdM: 3480,
    raiseDisplay: "€600m (2025 attempt)",
    ceo: "Rainer Birkenbach",
    ceoEmail: "rainer.birkenbach@brainlab.com",
    ceoEmailTier: "inferred",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: "first.last@brainlab.com",
    patternNote: "Domain confirmed (brainlab.com). Pattern assumed from German corporate convention, unverified.",
    verified: "2026-09-02",
    sources: [
      { label: "Börsen-Zeitung, Brainlab fires the starting gun for its IPO", url: "https://www.boersen-zeitung.de/english/brainlab-gives-the-green-light-for-its-ipo" }
    ]
  },

  /* ======================== DFM (Dubai) ================================== */
  {
    company: "Dubai Investments Park",
    exchange: "DFM",
    country: "United Arab Emirates",
    sector: "Real Estate",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Master-developer and operator of a 3,200-hectare mixed-use industrial, commercial and residential park in Dubai. Carve-out from listed parent Dubai Investments PJSC, which has confirmed it is still pursuing the listing while not fixing final timing.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Contact route runs through listed parent Dubai Investments PJSC investor relations.",
    verified: "2026-09-02",
    sources: [
      { label: "AGBI, Dubai Investments pushes ahead with DIP listing", url: "https://www.agbi.com/markets/2026/05/dubai-investments-pushes-ahead-with-dip-listing/" },
      { label: "The National, Middle East IPOs to bounce back in 2026", url: "https://www.thenationalnews.com/business/markets/2026/01/02/middle-east-ipos-to-bounce-back-in-2026-after-slump/" }
    ]
  },
  {
    company: "Dubizzle Group",
    exchange: "DFM",
    country: "United Arab Emirates",
    sector: "Internet & Classifieds",
    status: "Announced",
    listingDate: "2026",
    datePrecision: "year",
    description: "MENA's largest classifieds group, operating dubizzle, Bayut and Property Finder-adjacent portals across the UAE, Egypt and Pakistan. Postponed a 2025 listing and is tipped to return in 2026.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No listing-entity executive disclosure published.",
    verified: "2026-09-02",
    sources: [
      { label: "The National, Middle East IPOs to bounce back in 2026", url: "https://www.thenationalnews.com/business/markets/2026/01/02/middle-east-ipos-to-bounce-back-in-2026-after-slump/" }
    ]
  },
  {
    company: "Binghatti Holding",
    exchange: "DFM",
    country: "United Arab Emirates",
    sector: "Real Estate",
    status: "Rumoured",
    listingDate: "2026",
    datePrecision: "year",
    description: "Dubai luxury property developer known for branded residential towers, expanding into hospitality. Named among UAE candidates for the 2026 window.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No confirmed listing process; contacts not asserted.",
    verified: "2026-09-02",
    sources: [
      { label: "The National, Middle East IPOs to bounce back in 2026", url: "https://www.thenationalnews.com/business/markets/2026/01/02/middle-east-ipos-to-bounce-back-in-2026-after-slump/" }
    ]
  },

  /* ========================= B3 (Brazil) ================================= */
  {
    company: "Compass Gás e Energia",
    exchange: "B3",
    country: "Brazil",
    sector: "Energy",
    status: "Listed",
    listingDate: "2026-05-11",
    datePrecision: "day",
    description: "Brazil's leading natural gas distributor, comprising Comgás (São Paulo state distribution), gas marketing and midstream infrastructure. Listed on B3's Novo Mercado under ticker PASS3 in an entirely secondary offering by parent Cosan. Ended Brazil's five-year IPO drought.",
    valuationDisplay: "~R$20bn",
    valuationUsdM: 3700,
    raiseDisplay: "R$2.5–3.2bn",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Post-listing contact runs through the Cosan group investor relations function.",
    verified: "2026-09-02",
    sources: [
      { label: "Rio Times, Compass IPO ends Brazil's drought", url: "https://www.riotimesonline.com/compass-cosan-ipo-brazil-drought-b3-2026/" }
    ]
  },
  {
    company: "B3 pipeline (issuer not yet named)",
    exchange: "B3",
    country: "Brazil",
    sector: "Multiple",
    status: "Pipeline signalled",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "Following the Compass listing, bankers report a reopening Brazilian pipeline of candidates that had been shelved since 2021. No individual issuer has filed publicly as of the verification date. This row is retained deliberately: an empty exchange is itself information for a coverage list.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "Rio Times, Compass debuts on B3", url: "https://www.riotimesonline.com/compass-debuts-on-b3-monday-as-brazils-ipo-drought-ends/" }
    ]
  },

  /* ====================== KLSE (Bursa Malaysia) ========================== */
  {
    company: "SkyeChip Berhad",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "AI & Semiconductors",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Malaysia's first homegrown integrated-circuit design house, developing custom silicon and IP for AI and data-centre applications. Main Market listing priced at RM0.80 per share.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "~RM352m",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Executive detail sits in the Bursa prospectus, not in English press disclosure.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },
  {
    company: "KK Mart (KK Super Mart)",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "Consumer Staples",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "National convenience-store chain operating several hundred outlets across Malaysia. Pricing and listing date not yet confirmed.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Prospectus not yet public.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },
  {
    company: "MTT Shipping",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "Transport & Logistics",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Intra-Asia container shipping and logistics operator. One of the larger names in the Bursa pipeline; pricing and date to be confirmed.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Prospectus not yet public.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },
  {
    company: "EI Power",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "Energy",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Energy systems and power infrastructure contractor. Pricing and listing date to be confirmed.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Prospectus not yet public.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },
  {
    company: "Big Caring Group",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "Healthcare",
    status: "Announced",
    listingDate: "2026-H2",
    datePrecision: "half",
    description: "Community pharmacy and healthcare retail chain. Pricing and listing date to be confirmed.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Prospectus not yet public.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },
  {
    company: "Sunway Healthcare Holdings",
    exchange: "KLSE",
    country: "Malaysia",
    sector: "Healthcare",
    status: "Listed",
    listingDate: "2026-03-18",
    datePrecision: "day",
    description: "Private hospital group operating Malaysia's Sunway Medical network. The largest Bursa IPO of 2026 at RM2.86bn raised; priced at RM1.45 and closed its first day up 28% on 5.57x institutional oversubscription.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "RM2.86bn",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Now listed; contact runs through the company's investor relations function.",
    verified: "2026-09-02",
    sources: [
      { label: "IPO Malaysia 2026, Bursa listings", url: "https://calculatormalaysia.com/investment/ipo-malaysia-2026/" }
    ]
  },

  /* ======================== JSE (Johannesburg) =========================== */
  {
    company: "Dangote Refinery",
    exchange: "JSE",
    country: "Nigeria / South Africa",
    sector: "Energy",
    status: "Announced",
    listingDate: "2027",
    datePrecision: "year",
    description: "Operator of the 650,000 barrel-per-day Lekki refinery outside Lagos, Africa's largest. Plans a primary listing on the Nigerian Exchange first, with a stated intent to follow with a JSE secondary listing. Would be the continent's largest public offering.",
    valuationDisplay: "~$5bn",
    valuationUsdM: 5000,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "Listing entity and executive slate not yet disclosed.",
    verified: "2026-09-02",
    sources: [
      { label: "CNBC Africa, JSE courts Dangote Refinery listing", url: "https://www.cnbcafrica.com/2026/south-africas-jse-courts-dangote-refinery-listing" }
    ]
  },
  {
    company: "JSE pipeline (issuers not yet named)",
    exchange: "JSE",
    country: "South Africa",
    sector: "Multiple",
    status: "Pipeline signalled",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "JSE CEO Valdene Reddy has described a robust pipeline spanning mining, fintech, property and construction, REITs and infrastructure-linked instruments, alongside simplified listing rules introduced to cut issuer costs. No individual issuers have been named publicly.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "CNBC Africa, JSE courts Dangote Refinery listing", url: "https://www.cnbcafrica.com/2026/south-africas-jse-courts-dangote-refinery-listing" },
      { label: "JSE simplified listing requirements", url: "https://dabafinance.com/en/news/jse-simplified-listing-requirements-capital-markets" }
    ]
  },

  /* ===================== SGX / WSE / SET / TWSE ========================== */
  {
    company: "SGX pipeline: Nasdaq dual-listing fast track",
    exchange: "SGX",
    country: "Singapore",
    sector: "Multiple",
    status: "Pipeline signalled",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "SGX opened a fast-track Nasdaq dual-listing route from mid-2026 and reported a growing IPO pipeline alongside record half-year profit, but the S$2bn market-cap threshold may limit uptake. Chinese issuers are also exploring Singapore listings. No individual issuer has been publicly named for the window.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "Malay Mail, SGX Nasdaq fast-track dual listing", url: "https://www.malaymail.com/news/singapore/2026/01/09/singapores-nasdaq-fasttrack-draws-interest-but-high-s2b-threshold-may-curb-uptake/204737" },
      { label: "SGX record half-year profit, growing IPO pipeline", url: "https://in.marketscreener.com/news/singapore-exchange-logs-record-half-year-profit-highlights-growing-ipo-pipeline-ce7e5adbd98df624" }
    ]
  },
  {
    company: "WSE pipeline (defence issuer not yet named)",
    exchange: "WSE",
    country: "Poland",
    sector: "Defence",
    status: "Pipeline signalled",
    listingDate: "2026-Q4",
    datePrecision: "quarter",
    description: "The Warsaw Stock Exchange expects a clear revival in IPO activity in 2026, including the possibility of a significant defence-sector listing toward the end of the year, and increased activity from Central and Eastern European issuers. The specific issuer has not been disclosed.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "WFE Focus, Warsaw Stock Exchange 2026 agenda", url: "https://focus.world-exchanges.org/articles/warsaw-stock-exchange" }
    ]
  },
  {
    company: "SET pipeline: 3 approved, 3 submitted",
    exchange: "SET",
    country: "Thailand",
    sector: "Multiple",
    status: "Pipeline signalled",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "The Stock Exchange of Thailand's upcoming-IPO register shows three approved applications (two common stock, one REIT) and three submitted, with no filings yet at effective status. Issuer names are not published at the approved stage. The exchange is separately courting technology and AI listings and working to win back Thai companies that listed abroad.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named at this filing stage, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "SET, Upcoming IPO register", url: "https://www.set.or.th/en/listing/ipo/upcoming-ipo/set" },
      { label: "Thailand and Singapore exchanges seek tech listings", url: "https://kr-asia.com/thailand-singapore-exchanges-seek-tech-listings-as-ai-booms" }
    ]
  },
  {
    company: "TWSE pipeline (AI issuers not yet named)",
    exchange: "TWSE",
    country: "Taiwan",
    sector: "AI & Semiconductors",
    status: "Pipeline signalled",
    listingDate: "N/A",
    datePrecision: "unknown",
    description: "TWSE Chairman Lin has said AI-related companies will account for more than 40% of Taiwan's IPO listings in 2026, with the exchange positioning itself around the AI and semiconductor supply chain and its Taiwan Innovation Board. Individual issuers in the pipeline have not been publicly named.",
    valuationDisplay: "N/A",
    valuationUsdM: null,
    raiseDisplay: "N/A",
    ceo: "N/A",
    ceoEmail: null,
    ceoEmailTier: "none",
    cfo: "N/A",
    cfoEmail: null,
    cfoEmailTier: "none",
    emailPattern: null,
    patternNote: "No issuer named, so no contacts exist to record.",
    verified: "2026-09-02",
    sources: [
      { label: "TWSE Chairman Lin, AI IPO share to top 40% in 2026", url: "https://finance.biggo.com/news/UoH1lJ4BmHHDnbgy4VHS" },
      { label: "TWSE Taiwan Innovation Board", url: "https://www.twse.com.tw/TIB/en/news.html" }
    ]
  }
];

/* Exchange reference metadata: full names and cities for the filter and detail views. */
const EXCHANGE_META = {
  LSE:     { name: "London Stock Exchange",        city: "London",       flag: "GB" },
  WSE:     { name: "Warsaw Stock Exchange (GPW)",  city: "Warsaw",       flag: "PL" },
  DFM:     { name: "Dubai Financial Market",       city: "Dubai",        flag: "AE" },
  TADAWUL: { name: "Saudi Exchange (Tadawul)",     city: "Riyadh",       flag: "SA" },
  JSE:     { name: "Johannesburg Stock Exchange",  city: "Johannesburg", flag: "ZA" },
  B3:      { name: "B3 (Brasil, Bolsa, Balcão)",     city: "São Paulo",    flag: "BR" },
  SGX:     { name: "Singapore Exchange",           city: "Singapore",    flag: "SG" },
  TWSE:    { name: "Taiwan Stock Exchange",        city: "Taipei",       flag: "TW" },
  SET:     { name: "Stock Exchange of Thailand",   city: "Bangkok",      flag: "TH" },
  KLSE:    { name: "Bursa Malaysia",               city: "Kuala Lumpur", flag: "MY" },
  XETRA:   { name: "Deutsche Börse Xetra",         city: "Frankfurt",    flag: "DE" }
};

const DATA_AS_OF = "2026-09-02";
